spring:
  application:
    name: myblog-server

  # 数据库连接配置
  datasource:
    url: jdbc:postgresql://localhost:5432/blog_db
    username: spike
    password: spike
    driver-class-name: org.postgresql.Driver

  # Flyway配置
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

# MyBatis配置
mybatis:
  # 1. 自动扫描别名包
  # 这里的原理是：MyBatis 会扫描该包下的所有类，
  # 并自动将类名注册为别名（例如 User.java -> 别名 "User" 或 "user"）
  type-aliases-package: com.spike.blog.server.model.entity
  mapper-locations:
    - classpath:dao/*.xml
    - classpath:mapper/**/*.xml
  configuration:
    # 开启自动驼峰命名转换：published_at -> publishedAt
    map-underscore-to-camel-case: true
    # 打印 SQL 日志到控制台
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

